// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;
using trunk.Persistence;

namespace trunk.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180215115909_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("trunk.Core.Models.Model", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("MakeId");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("MakeId");

                    b.ToTable("Models");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Model");
                });

            modelBuilder.Entity("trunk.Core.Models.Feature", b =>
                {
                    b.HasBaseType("trunk.Core.Models.Model");


                    b.ToTable("Feature");

                    b.HasDiscriminator().HasValue("Feature");
                });

            modelBuilder.Entity("trunk.Core.Models.Make", b =>
                {
                    b.HasBaseType("trunk.Core.Models.Model");


                    b.ToTable("Make");

                    b.HasDiscriminator().HasValue("Make");
                });

            modelBuilder.Entity("trunk.Core.Models.Model", b =>
                {
                    b.HasOne("trunk.Core.Models.Make", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
